name: install-qt
on: push
jobs:
  install-qt:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - name: "Windows 2019"
            os: windows-2019
            qt-version: '5.15.2'
            arch: "win64_msvc2019_64"
            host: "windows"
    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '${{ matrix.config.qt-version }}'
          host: '${{ matrix.config.host }}'
          target: 'desktop'
          arch: '${{ matrix.config.arch }}'
          dir: '${{ github.workspace }}'
          archives: 'qtbase qtwinextras'
          setup-python: 'false'

      - name: Test
        shell: bash
        run: |
          echo QT_ROOT_DIR=${QT_ROOT_DIR}
          ls -la ${{ github.workspace }}
          ls -la ${{ github.workspace }}/Qt

