on: [ push ]

jobs:
  build_windows_latest:
    runs-on: windows-2019
    steps:
    - name: Create and check vsversion.ini
      shell: cmd
      run: |
        echo VS_VERSION=2019 > vsversion.ini
        echo VS_TYPE=Enterprise >> vsversion.ini
        echo === vsversions.ini contents begin ===
        TYPE vsversion.ini
        echo === vsversions.ini contents end ===

    - name: Set environment variables
      shell: cmd
      run: |
        echo "QTDIR=${{ github.workspace }}\Qt" >> %GITHUB_ENV%
        echo "QT_VERSION=5.15.2" >> %GITHUB_ENV%
        SET TEST_VAR=C:\\Temp\\Sub1\\Sub2
        ECHO %TEST_VAR%

    - name: Check environment variables
      shell: cmd
      run: |
        printf "%QTDIR%\n"
        printf "%QT_VERSION%\n"
        printf "%TEST_VAR%\n"
        echo QTDIR=%QTDIR%
        echo QT_VERSION=%QT_VERSION%
        echo TEST_VAR=%TEST_VAR%
        echo QTDIR=${{ github.QTDIR }}
        echo QT_VERSION=${{ github.QT_VERSION }}
        echo TEST_VAR=${{ github.TEST_VAR }}

    - name: Replace variables in msvcQtPath.props
      shell: cmd
      run: |
        DIR
        SET QTDIR=C:\\Temp\\Sub1\\Sub2
        powershell.exe setQtProperties.ps1 -inFile msvcQtPath.props.in -version %QT_VERSION%
        echo === msvcQtPath.props contents begin ===
        TYPE msvcQtPath.props
        echo === msvcQtPath.props contents end ===

