name: qt5-test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  qt5-test:
    strategy:
      matrix:
        os: [ macos-latest ]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        # Use bash login shell sourcing ~/.bash_profile
        shell: bash -leo pipefail {0}
    env:
      CC: clang
      CXX: clang++

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Install packages
        if: runner.os == 'macOS'
        run: |
          brew install qt@5
          export PKG_CONFIG_PATH="$HOMEBREW_PREFIX/opt/qt@5/lib/pkgconfig"
          echo "$HOMEBREW_PREFIX/opt/qt@5/bin" >> $GITHUB_PATH

      - name: Context
        if: runner.os == 'macOS'
        run: |
          uname -a
          sysctl hw.physicalcpu
          sysctl hw.logicalcpu
          echo "PATH:" $PATH
          echo "GITHUB_PATH:" $GITHUB_PATH
          echo "HOMEBREW_PREFIX:" $HOMEBREW_PREFIX
          cmake --version
          ls -la $HOMEBREW_PREFIX/opt/qt@5/
          ls -la $HOMEBREW_PREFIX/opt/qt@5/lib/
          ls -la $HOMEBREW_PREFIX/opt/qt@5/mkspecs/

      - name: Configure
        if: runner.os == 'macOS'
        run: |
          mkdir bld
          cd bld
          cmake .. -DCMAKE_PREFIX_PATH=$HOMEBREW_PREFIX/opt/qt@5

