on: [ push ]

jobs:
  build_windows_latest:
    env:
      QTDIR: ${{ github.workspace }}\Qt
    runs-on: windows-2019
    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Create and check vsversion.ini
      shell: cmd
      run: |
        echo VS_VERSION=2019 > vsversion.ini
        echo VS_TYPE=Enterprise >> vsversion.ini
        echo === vsversions.ini contents begin ===
        TYPE vsversion.ini
        echo === vsversions.ini contents end ===

    - name: Set environment variables
      shell: cmd
      run: |
        printf "QT_VERSION=5.15.2\n" >> %GITHUB_ENV%
        printf "TEST_VAR=C:\\Temp\\Sub1\\Sub2\n" >> %GITHUB_ENV%

    - name: Check environment variables
      shell: cmd
      run: |
        printf "%QTDIR%\n"
        printf "%QT_VERSION%\n"
        printf "%TEST_VAR%\n"
        echo QTDIR=%QTDIR%
        echo QT_VERSION=%QT_VERSION%
        echo TEST_VAR=%TEST_VAR%
        echo QT_VERSION=${{ env.QT_VERSION }}
        echo TEST_VAR=${{ env.TEST_VAR }}
        echo QT_VERSION=%QT_VERSION%
        echo TEST_VAR=%TEST_VAR%

    - name: Replace variables in msvcQtPath.props
      shell: cmd
      run: |
        DIR
        echo QTDIR=%QTDIR%
        powershell.exe ./setQtProperties.ps1 -inFile msvcQtPath.props.in -version ${{ env.QT_VERSION }}
        echo === msvcQtPath.props contents begin ===
        TYPE msvcQtPath.props
        echo === msvcQtPath.props contents end ===

